version: '3.7'
services:
  web:
    container_name: forum_service_web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/home/app:delegated
    ports:
      - 5001:3000
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgres://root:password@db:5432/karibu_forum  # poor database name here...
    depends_on:  
      - db
      - redis

  db:
    container_name: forum_service_postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ~/.postgres_data/karibu_forum_service:/var/lib/postgresql/data:delegated
    ports:
      - 9001:5432

  redis:
    container_name: forum_redis
    image: redis:5-alpine

  worker:
    build:
      context: .
      dockerfile: ./infra/Dockerfile-worker-dev
    volumes:
      - $PWD:/home/app:delegated
    depends_on:
      - redis
    environment:
      - DEVELOP
      - AUTORELOAD
      - APP_ENV=development
      - DATABASE_URL=postgres://root:password@db:5432/karibu_forum